# Generated by Django 4.1.2 on 2022-10-11 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_item_price_currency_item_sell_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.item'),
        ),
    ]
