# Generated by Django 4.1.2 on 2022-10-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attributevalue_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_id',
            new_name='user',
        ),
    ]
